export const Customers = [
    {
        id: 1,
        name: 'Alex Gordon',
        budget: '2,500,000',
        phone: '0548099631',
        rooms: '2-3',
        floor: '2',
        elevator: true,
        parking: false,
    },
    {
        id: 2,
        name: 'Ziva Frits',
        budget: '3,500,000',
        phone: '0538899554',
        rooms: '3',
        floor: '1',
        elevator: true,
        parking: true,
    },
    {
        id: 3,
        name: 'Shahar Bechor',
        budget: '4,500,000',
        phone: '0542266898',
        rooms: '4',
        floor: '2',
        elevator: false,
        parking: false,
    },
    {
        id: 4,
        name: 'Tim Benington',
        budget: '3,500,000',
        phone: '052996898',
        rooms: '3',
        floor: '3',
        elevator: true,
        parking: true,
    },
    {
        id: 5,
        name: 'Tom Riddle',
        budget: '8,000,000',
        phone: '053656545',
        rooms: '5',
        floor: '4',
        elevator: true,
        parking: true,
    }
]