export const USER_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  ADD_PROPERTY: 'ADD_PROPERTY',
  SORT_BY_PARAMETER: 'SORT_BY_PARAMETER',
  DELETE_DATA: 'DELETE_DATA',
  UPDATE_DATA: 'UPDATE_DATA',
  SEARCH_DATA: 'SEARCH_DATA'
};
