export const USER_TYPES = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  ADD_CUSTOMER: 'ADD_CUSTOMER',
  ADD_PROPERTY: 'ADD_PROPERTY',
  SORT_BY_BUDGET_DOWN: 'SORT_BY_BUDGET_DOWN',
  SORT_BY_BUDGET_UP: 'SORT_BY_BUDGET_UP',
  SORT_BY_NAME: 'SORT_BY_NAME',
  DELETE_DATA: 'DELETE_DATA',
  UPDATE_DATA: 'UPDATE_DATA',
  SEARCH_DATA: 'SEARCH_DATA'
};
